# Filename: Dockerfile
#sets the base image from which the Docker container will be created.
ARG DOCKER_BASE_IMAGE=openjdk:11-jre-slim
FROM $DOCKER_BASE_IMAGE
MAINTAINER vknukala
#set the path of the extracted jar contents generated by maven build comannd to to LAYER variable.
ARG LAYER=target/layers
#copies the contents of lib folder created after running maven build command to the docker-demo/lib folder inside the docker container.
COPY ${LAYER}/BOOT-INF/lib /docker-demo/lib
#copies the contents of META-INF folder created after running maven build command to the docker-demo/META-INF folder inside the docker container.
COPY ${LAYER}/META-INF /docker-demo/META-INF
#copies the contents of classes folder created after running maven build command to the docker-demo folder inside the docker container.
COPY ${LAYER}/BOOT-INF/classes /docker-demo
#exec form without invoking command shell
ENTRYPOINT ["java","-cp","docker-demo:docker-demo/lib/*","com.github.vknukala.docker.Application"]